### ISSUE TITLE
Random White Theme

### ISSUE THREAD

**Issue by togoshigekata** [biblepay/BiblePayPool#9]
When using the pool website, sometimes an action will lead to the page turning to a white theme, 
also when opening a 2nd tab of the pool when another one is open, the 2nd tab will be white

Also the menus open up

Using latest Chrome Version 67.0.3396.99

Picture of White Page:
https://i.imgur.com/s72Q077.png
![biblepay_pool_white_1](https://user-images.githubusercontent.com/2773182/42413425-409e31d0-81e5-11e8-8bbf-894da34fdee4.png)

**Comment by leetlezee** [comment]
I get this error as well. According to the dev, it's because the site uses insitu callbacks, which doesn't interface with browser navigation, so you can't use the back button on the browser or the website will show up like this. You can try CTRL+F5, if that doesn't work, you will have to clear your cookies. Although just waiting a certain amount of time will also fix the error (not positive on this exact time frame).

**Comment by biblepay** [comment]
Thanks for the heads up - Let me do a little testing and see if we can capture the f5 and the browser back button the way facebook does.....

**Comment by biblepay** [comment]
Ok, the root of the problem is that people press f5 on this site (since this is a more modern design using ajax and callbacks, the css wasnt being reloaded into the head).  In this case we usually handle the f5 and back button (in a similar way that other more modern sites that use callbacks like facebook do).  (In contrast to not having to handle it on Older sites from the 90s that use navigation and frames, which is something we dont do.  Our frames are all html5 by requirement - meaning they were added to pull in Off site content - like twitter or compassion)

So now when you press f5 you get a warning; then the site reloads with css, therefore the problem should be mitigated.
